# Generated by Django 4.2.11 on 2024-03-08 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('name_task', models.CharField(max_length=255, null=True)),
                ('des_task', models.CharField(max_length=455, null=True)),
                ('start_date_task', models.DateField(null=True)),
                ('start_time_task', models.TimeField(null=True)),
                ('end_date_task', models.DateField(null=True)),
                ('end_time_task', models.TimeField(null=True)),
                ('pers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taches.user')),
            ],
        ),
    ]
