# Generated by Django 4.2.11 on 2024-03-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=255, null=True)),
                ('des_task', models.CharField(max_length=455, null=True)),
                ('start_date_task', models.DateField(null=True)),
                ('start_time_task', models.TimeField(null=True)),
                ('end_date_task', models.DateField(null=True)),
                ('end_time_task', models.TimeField(null=True)),
                ('statut_task', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='task',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
